name: rework_2021
description: Github page rework 2021

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.2

flutter:
  uses-material-design: true

