gitHub:
  clientId: "c2574b6003fe1f96228c"
  clientSecret: "eb6a1a0a05ad8d56d19ea69e4afe592f8a17fab5"

pages:
  about:
    title:
      en: "About"
      ru: "О себе"
    path: assets/pages/about.md

categories:
  -
    name:
      en: "Learning"
      ru: "Изучение"
  -
    name:
      en: "Example"
      ru: "Примеры"

tags:
  - Dart
  - Dart VM

articles:
  -
    date: "2015/08/05"
    category: "learning"
    tags:
      - Dart
      - Dart VM
    title:
      en: "The Dart VM execution model"
      ru: "Dart VM модель исполнения"
    path: assets/articles/learning/the_dart_vm_execution_model.md
