name: release
on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Create
        run: flutter create --platforms web --project-name rework_2021 .

      - name: Get packages
        run: flutter pub get

#     - name: Analyze Dart
#       uses: zgosalvez/github-actions-analyze-dart@v1

#      - name: Run tests
#        run: flutter test

      - name: Build web
        run: flutter build web --release

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: application
          path: build/web

  deploy:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: application

      - name: Push changes
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main
          FOLDER: application
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

